[package]
name = "payments"
version = "0.1.0"
edition = "2021"


[dependencies]
csv = "1.3.0"
env_logger = "0.11.5"
log = "0.4.22"
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"
serde = {version = "1.0.213", features = ["derive"]}

